FROM lcr.loongnix.cn/library/rust:1.97.1

RUN apt-get update && apt-get install -y \
    bash \
    sed \
    wget \
    git \
    coreutils \
    gcc \
    libc6-dev \
    libseccomp-dev \
    lld \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["/bin/bash"]
